### ISSUE TITLE
~10% stale shares when mining on grinmint.com pool

### ISSUE THREAD

**Issue by spacetrain** [NebuTech/NBMiner#100]
When mining grin31 on sparkpool, it shows only ~0.05% stale shares.
But when mining on grinmint pool, it shows up to 10% of stale shares.
I am currently running 5 rigs and interestingly when there happens a stale share, it appears on all of my rigs almost simultaneously.
I don't think it as a network latency problem because my networking setup is very stable.
Any chance to resolve this?

**Comment by nebutech-admin** [comment]
@spacetrain After analyzed log, I found the cause is the new job sent from Grinmint could has the same `job_id` as other job, but differs in `height`.
NBMiner distinguishes jobs only by `job_id`.
It's more of a conventional inconformity, will be fixed in the next version.
