### ISSUE TITLE
Нестабильный майнинг

### ISSUE THREAD

**Issue by 5000VID** [NebuTech/NBMiner#101]
On the farm of 6 pcs. GTX1080ti when you start mining for more than 3pcs of video cards, the farm often goes into reboot (Windows 10, 8GB RAM). With 3 video cards, it works stably. These are protocols Cyckooro 29 \ 31 and CykooCyckl. Mine on NiceHash. How to start running stable 6 pieces of video cards?

**Comment by nebutech-admin** [comment]
The situation often dues to one of your GPUs is not in a health condition.
Try filter GPUs with something lile `-d 0,1,2 `, rule out one card each time to see which is it.
