### ISSUE TITLE
grin29 fork nicehash rejects nbminer 24.1

### ISSUE THREAD

**Issue by bercutes** [NebuTech/NBMiner#105]
grin29 after fork "share above target", rejects, another miner work

**Comment by nebutech-admin** [comment]
@bercutes When you set algo to cuckarood, will that happen?

**Comment by bercutes** [comment]
set "cuckarood" need in algo setting?
nothing after start accept shares but then restart for new algo and rejects all "shares above target"

**Comment by bercutes** [comment]
set "cuckarood" need in algo setting?
nothing after start accept shares but then restart for new algo and rejects all "shares above target"

**Comment by nebutech-admin** [comment]
@bercutes Can you post a screenshot?

**Comment by bercutes** [comment]
![63473](https://user-images.githubusercontent.com/40851736/61376940-e4520d00-a8aa-11e9-8a5c-b206956b1802.png)

**Comment by nebutech-admin** [comment]
use grincuckarood29 in url, not grincuckaroo29, algo on nicehash also changed.

**Comment by bercutes** [comment]
another miner work with old adress nicehash, now i try grincuckarood29 - login failed disconnect

**Comment by nebutech-admin** [comment]
grincuckaroo29 won't make any profits now, switch to 29d.

**Comment by Minerx117** [comment]
Grin29d is ONLY enabled on NiceHash New Platform not supported in NiceHash old platform

**Comment by bercutes** [comment]
old adress not old nicehash, old url without "d" in algo
another miner work with url without "d" on new nicehash platform

**Comment by bercutes** [comment]
another miner that work 
miner.exe --algo cuckaroo29 --server grincuckaroo29.eu-new.nicehash.com --port 3371 --user

**Comment by nebutech-admin** [comment]
If you choose to stick on cuckaroo algo with v24.1, you can set the `--grin29-fork-height` to a big number like 10000000.
Or wait for a v24.2 soon.
