### ISSUE TITLE
-v / --version does not output version on linux.

### ISSUE THREAD

**Issue by melt7777** [NebuTech/NBMiner#106]
Hello and thanks for the great work on your miner. I was working with it for integrating into PiMP OS, and I found that the --version flag is not putting out the version of the miner. This is important to have, and we hope that you can accommodate this request to repair it. 

Here is sample output - the latest release available in this repo, 24.2, running on PiMP OS v2.11, based on Ubuntu 18.04 LTS, fully upgraded to today's packages: 

[/opt/miners/nbminer]:# ls
logs                    OhGodAnETHlargementPill-r2  start_ae.sh       start_config.sh  start_grin31.sh
nbminer                 readme.md                   start_btm_eth.sh  start_eth.sh     start_sero.sh
NBMiner_24.2_Linux.tgz  readme_zh.md                start_btm.sh      start_grin29.sh  start_swap.sh
[Agent: m204-2.11-mix (Running) Total HR: [0.00Kh/s] Miners running [0] GPUs [none active]]
[11:03 PM][Uptime: 2d 2:13][root@pimp3(10.0.0.204)]
[/opt/miners/nbminer]:# ./nbminer --version
Usage: ./nbminer [options]
Typical usage:
./nbminer -a <algo> -o <url> -u <wallet.worker[:password]>
BTM: ./nbminer -a tensority -o stratum+tcp://btm.matpool.io:8118 -u bm1xxxxxxxxxxxx.worker
ETH: ./nbminer -a ethash -o ethproxy+tcp://eth.f2pool.com:8008 -u 0xxxxxxxxxxxxx.worker
BTM+ETH: ./nbminer -a tensority_ethash -o stratum+tcp://btm.matpool.io:8118 -u bm1xxxxxxxxxxxx.worker -do ethproxy+tcp://eth.f2pool.com:8008 -du 0xxxxxxxxxxxxx.worker
Grin29: ./nbminer -a cuckaroo -o stratum+tcp://grin.sparkpool.com:6666 -u email/worker
Grin31: ./nbminer -a cuckatoo -o stratum+tcp://grin.sparkpool.com:6667 -u email/worker
AE: ./nbminer -a cuckoo_ae -o stratum+tcp://ae.f2pool.com:7898 -u ak_xxxxxx.worker:passwd
SWAP: ./nbminer -a cuckaroo_swap -o stratum+tcp://swap2.luckypool.io:4466 -u wallet.worker

Options:
  -h, --help                               Displays this help.
  -v, --version                            Displays version information.
  -c, --config <config file path>          Use config file rather than cmd line
                                           options.
  --generate-config <filename>             Generate a sample config file.
  --api <host:port>                        The endpoint for serving REST API.
  -d, --devices <devices>                  Specify GPU list to use. Example:
                                           "-d 0,1,2,3" to use first 4 GPU.
  -a, --algo <algo>                        Algorithm to mining. Supported
                                           algos:
                                           * tensority
                                           * ethash
                                           * tensority_ethash
                                           * cuckaroo
                                           * cuckarood
                                           * cuckatoo
                                           * cuckoo_ae
                                           * cuckaroo_swap
                                           * progpow_sero
  -o, --url <url>                          Mining pool url. Example:
                                           stratum+tcp://btm.f2pool.com:9221
                                           stratum+ssl://btm.f2pool.com:9443
                                           ethproxy+tcp://eth.f2pool.com:8008
                                           nicehash+tcp://daggerhashimoto.eu.nic
                                           ehash.com:3353
  --o1, --url1 <url>                       Backup url 1.
  --o2, --url2 <url>                       Backup url 2.
  -u, --user <user>                        User used in mining pool. Example:
                                           [wallet]
                                           bm1qjcexxxxxxxxxxxxx.rigName:password
                                           [username] miner_test.rigName
  --u1, --user1 <user>                     Backup user 1.
  --u2, --user2 <user>                     Backup user 2.
  --do, --secondary-url <url>              Mining pool for secondary algorithm.
  --du, --secondary-user <user>            User for secondary algorithm.
  --do1, --secondary-url1 <url>            Backup url 1 for secondary
                                           algorithm.
  --do2, --secondary-url2 <url>            Backup url 2 for secondary
                                           algorithm.
  --du1, --secondary-user1 <user>          Backup user 1 for secondary
                                           algorithm.
  --du2, --secondary-user2 <user>          Backup user 2 for secondary
                                           algorithm.
  -i, --intensity <intensities>            Comma-separated list of intensities
                                           (1-100).
  --di, --secondary-intensity <intensity>  Intensity of secondary algorithm.
  --log                                    Generate log file named
                                           'log_<timestamp>.txt'.
  --log-file <logfile>                     Generate custom log file. Note: This
                                           option will override '--log'.
  --long-format                            Use 'yyyy-MM-dd HH:mm:ss,zzz' for
                                           log time format.
  --no-color                               Do not use colorful output log in
                                           cmd line.
  --no-nvml                                Do not query cuda device health
                                           status.
  --strict-ssl                             Use strict SSL certificate check
                                           when use ssl connections.
  --temperature-limit <temp-limit>         Set temperature limit of GPU, if
                                           exceeds, stop GPU for 10 sec and
                                           continue.
  --fidelity-timeframe <timeframe>         Set timeframe for the calculation of
                                           fidelity, unit in hour. Default: 24.
  --device-info                            Print out detailed information for
                                           every device.
  --device-info-json                       Print out detailed information for
                                           every device in json format.
  --RUN, --no-watchdog                     Disable watchdog process.
  --reboot-times <reboot-times>            Passed by watchdog process to count
                                           the miner reboot times.
  --cuckoo-intensity <intensity>           Set intensity of cuckoo, cuckaroo,
                                           cuckatoo, [1, 12]. Set to 0 means
                                           autumatically adapt. Default: 4.
  --cuckatoo-power-optimize                Set this option to reduce the range
                                           of power consumed by rig when
                                           minining with algo cuckatoo.
                                           Warning: Setting this option may
                                           cause drop on minining performance.
[Agent: m204-2.11-mix (Running) Total HR: [0.00Kh/s] Miners running [0] GPUs [none active]]
[11:06 PM][Uptime: 2d 2:16][root@pimp3(10.0.0.204)]
[/opt/miners/nbminer]:# ./nbminer -v
Usage: ./nbminer [options]
Typical usage:
./nbminer -a <algo> -o <url> -u <wallet.worker[:password]>
BTM: ./nbminer -a tensority -o stratum+tcp://btm.matpool.io:8118 -u bm1xxxxxxxxxxxx.worker
ETH: ./nbminer -a ethash -o ethproxy+tcp://eth.f2pool.com:8008 -u 0xxxxxxxxxxxxx.worker
BTM+ETH: ./nbminer -a tensority_ethash -o stratum+tcp://btm.matpool.io:8118 -u bm1xxxxxxxxxxxx.worker -do ethproxy+tcp://eth.f2pool.com:8008 -du 0xxxxxxxxxxxxx.worker
Grin29: ./nbminer -a cuckaroo -o stratum+tcp://grin.sparkpool.com:6666 -u email/worker
Grin31: ./nbminer -a cuckatoo -o stratum+tcp://grin.sparkpool.com:6667 -u email/worker
AE: ./nbminer -a cuckoo_ae -o stratum+tcp://ae.f2pool.com:7898 -u ak_xxxxxx.worker:passwd
SWAP: ./nbminer -a cuckaroo_swap -o stratum+tcp://swap2.luckypool.io:4466 -u wallet.worker

Options:
  -h, --help                               Displays this help.
  -v, --version                            Displays version information.
  -c, --config <config file path>          Use config file rather than cmd line
                                           options.
  --generate-config <filename>             Generate a sample config file.
  --api <host:port>                        The endpoint for serving REST API.
  -d, --devices <devices>                  Specify GPU list to use. Example:
                                           "-d 0,1,2,3" to use first 4 GPU.
  -a, --algo <algo>                        Algorithm to mining. Supported
                                           algos:
                                           * tensority
                                           * ethash
                                           * tensority_ethash
                                           * cuckaroo
                                           * cuckarood
                                           * cuckatoo
                                           * cuckoo_ae
                                           * cuckaroo_swap
                                           * progpow_sero
  -o, --url <url>                          Mining pool url. Example:
                                           stratum+tcp://btm.f2pool.com:9221
                                           stratum+ssl://btm.f2pool.com:9443
                                           ethproxy+tcp://eth.f2pool.com:8008
                                           nicehash+tcp://daggerhashimoto.eu.nic
                                           ehash.com:3353
  --o1, --url1 <url>                       Backup url 1.
  --o2, --url2 <url>                       Backup url 2.
  -u, --user <user>                        User used in mining pool. Example:
                                           [wallet]
                                           bm1qjcexxxxxxxxxxxxx.rigName:password
                                           [username] miner_test.rigName
  --u1, --user1 <user>                     Backup user 1.
  --u2, --user2 <user>                     Backup user 2.
  --do, --secondary-url <url>              Mining pool for secondary algorithm.
  --du, --secondary-user <user>            User for secondary algorithm.
  --do1, --secondary-url1 <url>            Backup url 1 for secondary
                                           algorithm.
  --do2, --secondary-url2 <url>            Backup url 2 for secondary
                                           algorithm.
  --du1, --secondary-user1 <user>          Backup user 1 for secondary
                                           algorithm.
  --du2, --secondary-user2 <user>          Backup user 2 for secondary
                                           algorithm.
  -i, --intensity <intensities>            Comma-separated list of intensities
                                           (1-100).
  --di, --secondary-intensity <intensity>  Intensity of secondary algorithm.
  --log                                    Generate log file named
                                           'log_<timestamp>.txt'.
  --log-file <logfile>                     Generate custom log file. Note: This
                                           option will override '--log'.
  --long-format                            Use 'yyyy-MM-dd HH:mm:ss,zzz' for
                                           log time format.
  --no-color                               Do not use colorful output log in
                                           cmd line.
  --no-nvml                                Do not query cuda device health
                                           status.
  --strict-ssl                             Use strict SSL certificate check
                                           when use ssl connections.
  --temperature-limit <temp-limit>         Set temperature limit of GPU, if
                                           exceeds, stop GPU for 10 sec and
                                           continue.
  --fidelity-timeframe <timeframe>         Set timeframe for the calculation of
                                           fidelity, unit in hour. Default: 24.
  --device-info                            Print out detailed information for
                                           every device.
  --device-info-json                       Print out detailed information for
                                           every device in json format.
  --RUN, --no-watchdog                     Disable watchdog process.
  --reboot-times <reboot-times>            Passed by watchdog process to count
                                           the miner reboot times.
  --cuckoo-intensity <intensity>           Set intensity of cuckoo, cuckaroo,
                                           cuckatoo, [1, 12]. Set to 0 means
                                           autumatically adapt. Default: 4.
  --cuckatoo-power-optimize                Set this option to reduce the range
                                           of power consumed by rig when
                                           minining with algo cuckatoo.
                                           Warning: Setting this option may
                                           cause drop on minining performance.
[Agent: m204-2.11-mix (Running) Total HR: [0.00Kh/s] Miners running [0] GPUs [none active]]
[11:06 PM][Uptime: 2d 2:17][root@pimp3(10.0.0.204)]
[/opt/miners/nbminer]:# 

Thank you very much,
~ melt
getpimp.org | miner.farm

**Comment by melt7777** [comment]
I am very disappointed to see you close our issue without response. 

Not to mention this is not something I should have to request.

~ melt
getpimp.org | miner.farm

**Comment by nebutech-admin** [comment]
@melt7777 
Sorry for that inappropriate act. 
Thanks for the work to integrate NBMiner in your OS.
The issue is fixed in latest version.
Please feel free to join on discord channel to get more responsive communication.

**Comment by melt7777** [comment]
Excellent! We'll get back to work on integration. Thank you for the fix, and for your update. 💯 

~ melt
getpimp.org | miner.farm
