### ISSUE TITLE
Runing all cards separatelly 8x 1080Ti Win7

### ISSUE THREAD

**Issue by Strunczez** [NebuTech/NBMiner#107]
Runing all cards seperatelly leeds to system crash. Windows 7. 8x 1080Ti.
It is probably due to NVML time out during initial GPU query. It takes too long and miner is restarting.
Ealier version was working fine.

**Comment by Strunczez** [comment]
Runing all cards seperatelly leeds to system crash. Windows 7. 8x 1080Ti.
It is probably due to NVML time out during initial GPU query. It takes too long and miner is restarting.

**Comment by nebutech-admin** [comment]
@Strunczez Can you post a screenshot?

**Comment by Strunczez** [comment]
![crash](https://user-images.githubusercontent.com/15833714/61807616-2abee300-ae3a-11e9-9740-46dd245c0203.png)
Disconnected 4 GPU's and same effect.
4'th gpu cannot manage to start. Getting information of #ID0, ID1,ID2 takes forever then it crash due to timeout.
GPU overclock settings are bring back to stock.
When menadged to run 4 cards, then on 5'th card it took forever x2 then system crashed.

**Comment by Strunczez** [comment]
Any progress with that?
