### ISSUE TITLE
0 hashrate shown when dual mining

### ISSUE THREAD

**Issue by biGGer** [NebuTech/NBMiner#109]
I have 4 RTX 2060 and i'm getting 0 h/s shown both in console and api when trying to dual-mine Bytom on F2Pool and ETH on NiceHash.
![image](https://user-images.githubusercontent.com/412860/62429081-3eb8ed80-b734-11e9-84d2-87f627484105.png)

**Comment by nebutech-admin** [comment]
Confirmed with 24.1 & 24.2.
Work around is to use 24.0 and previous versions to mining BTM+ETH.
Will be fixed in the next version.
