### ISSUE TITLE
-a doesn't seem to work (anyone using this miner?)

### ISSUE THREAD

**Issue by aleqx** [NebuTech/NBMiner#115]
tried v26.0 out of curiosity, on Ubuntu 16.04

```
./nbminer -a cuckatoo -o stratum+tcp://host:port -u login:pass --no-nvml -d 0,1,2,3,4,5,6,7,8
```

It exists saying:

```
flag provided but not defined: -a
```

Also tried `--algo` and it says "flag provided but not defined: -algo" (note the single dash, whereas I specified two dashes)

**Comment by nebutech-admin** [comment]
@aleqx Can you post a screenshot?

**Comment by aleqx** [comment]
> @aleqx Can you post a screenshot?

There's nothing else other than what I already posted, except the pool url and my username, which I'm not going to share with you. If you don't believe the error then you should try mining cuckoo c31 yourself.

Mining c29d works. c31 doesn't.

**Comment by nebutech-admin** [comment]
@aleqx It's not that I don't believe it, I just can't reproduce the issue you described in same environment.
![image](https://user-images.githubusercontent.com/39877212/67266996-07144300-f4e4-11e9-8592-d7a7a25f4e97.png)

**Comment by aleqx** [comment]
Try with eu-de02.miningrigrentals.com:3322 (pool at mrr was luxor)

**Comment by nebutech-admin** [comment]
@aleqx Pool should matter here, if an cmd option is not recognized, it won't even try to login.
Can you try the start_grin31.sh file packed along with the miner?

**Comment by aleqx** [comment]
> @aleqx Pool shouldn't matter here, if an cmd option is not recognized, it won't even try to login.

Well, I get "flag provided but not defined: -a" when using

```
./nbminer -a cuckatoo -o stratum+tcp://eu-de02.miningrigrentals.com:3322 -u user.rigid:x --no-nvml -d 0,1,2,3,4,5,6,7,8
```

Where `user.rigid` are the mrr user and rig id. You should try it.
