### ISSUE TITLE
AMD gpus not initializing

### ISSUE THREAD

**Issue by pstarSR** [NebuTech/NBMiner#117]
downloaded latest version to do some ETH+CKB mining. CKB works fine, but ETH wont initialize the gpus.

I run the ETH+CKB.bat and it fails, log shows nothing. 
I run the ETH.bat, fails but states GPUS could not be initialized. NO GPUS found

I run CKB.bat alone. runs fine. finds all the GPUs and mines. 

This is a system that has mined ETH, and others. 
Amd Rx series cards ( 480/570/580 ) 
adrenaline 19.9.2 drivers
windows 10

I tried to force the devices with "-d 0,1,2,3," no luck.

**Comment by nebutech-admin** [comment]
Fixed in v26.2.
