### ISSUE TITLE
Vega56 declines in the new 26.2 version.

### ISSUE THREAD

**Issue by JeffreyChu2009** [NebuTech/NBMiner#119]
I'm using a gtx1066 and a vega56 to mine at sparkpool, and I've just receive the updated news from sparkpool(their service is really up to date).

I'm very excited to know that the new version enhance the AMD card's hashrate when mining ckb+eth. But to my surpriese, 26.2 makes the vega56 **weaker** than it was in 26.1, why?

We can see that it was around **260Mh/s** for ckb and **32Mh/s** for eth in the old 26.1 version below.

But it declines to around **200Mh/s** for ckb and **25Mh/s** for eth in the new 26.2 version.

I use exactly the same params for the two versions, and I hope it's my mistake to get this wrong result, and welcome any friends to help me with this strange issue. The new 26.2 version **does raise the gtx1066's hashrate a little bit**, BTW.

Thank you in advance :-)

**Comment by nebutech-admin** [comment]
@JeffreyChu2009 Sorry for unclear declaration for 26.2 release note.
The fact is 26.2 is tuned exclusively for Ellesmere cards, which are RX470 - RX 590.
Thees tuned params may cause lower hashrate for other AMD GPUs, which were not covered in out test yet.
We'll try fix this in future updates.

**Comment by JeffreyChu2009** [comment]
> @JeffreyChu2009 Sorry for unclear declaration for 26.2 release note.
> The fact is 26.2 is tuned exclusively for Ellesmere cards, which are RX470 - RX 590.
> Thees tuned params may cause lower hashrate for other AMD GPUs, which were not covered in out test yet.
> We'll try fix this in future updates.

OK, I'm using back to 26.1 now. And please take Vega64/56 users into consideration in NBMiner's future releases. Thx a lot in advance.

**Comment by nebutech-admin** [comment]
Fixed.
