### ISSUE TITLE
980ti cann't work

### ISSUE THREAD

**Issue by bxdx** [NebuTech/NBMiner#121]
windows ,v26.2
nbminer.exe --device-info
============== Devices Information ==============
|ID|CC|Memory|SM|CoreClk|MemClk|MBus|L2Cache|TCC|
| 0|52| 6144M|22|  1076M| 3505M| 384|  3072K| NO| 1:0:0 GeForce GTX 980 Ti
=================================================
when i mined cbk,it reported "ERROR - No OpenCL kernel for Device: GeForce GTX 980 Ti."
mining eth ,it reported "ERROR - CUDA Error: device kernel image is invalid (err_no=200)
[23:47:56] ERROR - Device 0 exception, exit ..."

1080ti works.

**Comment by nebutech-admin** [comment]
@bxdx 
As described in readme. Only NVIDIA GPUs with compute compatibility greater than 6.0 is supported.
