### ISSUE TITLE
Enhance --device-info command for easier AMD integration into NHM

### ISSUE THREAD

**Issue by S74nk0** [NebuTech/NBMiner#125]
Hello,

We would like to enable AMD devices with [NBMiner plugin](https://github.com/nicehash/NiceHashMiner/tree/master/src/Miners/NBMiner) for NiceHashMiner.

Could you enhance the `--device-info` command to include AMD devices as well? For us thew most important information is the miner ID and the device PCIe bus ID so we can cross-reference them correctly.

Thank you!

**Comment by nebutech-admin** [comment]
@S74nk0 Will be done in the next version soon.

**Comment by nebutech-admin** [comment]
@S74nk0 Sorry for late reply.
Fulfilled in 27.0

**Comment by S74nk0** [comment]
Thanks we will update the plugin
