### ISSUE TITLE
NBMiner version 27.3 \ Error while trying to run on different graphics cards

### ISSUE THREAD

**Issue by BARUCHER777** [NebuTech/NBMiner#131]
NBMiner version 27.3
An error occurred while trying to run on different graphics cards.
Unable to start mining on Nvidia 2070 super.
![NBMiner-v-27-3_Error](https://user-images.githubusercontent.com/18327150/75463459-e9c21a80-5996-11ea-81c2-afc2285a3e9e.jpg)

**Comment by nebutech-admin** [comment]
@BARUCHER777 Will this happen on previous versions?

**Comment by BARUCHER777** [comment]
Will this happen on previous versions?
On version 27.2 the same error

**Comment by nebutech-admin** [comment]
@BARUCHER777 Please try reinstall Nvidia driver and retry mining.

**Comment by nebutech-admin** [comment]
@BARUCHER777 A bug has found if you got AMD & NVIDIA mix rig and the AMD gpu has a smaller pci id than Nvidia GPU. Maybe this is your case.

**Comment by BARUCHER777** [comment]
Reinstalled drivers .... the error is still the same!

**Comment by nebutech-admin** [comment]
@BARUCHER777 FIxed in v27.4.
