### ISSUE TITLE
Nicehash Ethash stratum protocol and vardiff

### ISSUE THREAD

**Issue by pinpins** [NebuTech/NBMiner#133]
Does someone know if NBMiner supports Ethash mining with vardiff on Nicehash protocol?

From my tests I observed that miner using NH proposed stratum protocol does not respond to difficulty change during mining process and rather stick to fixed one provided at the beginning

Hence question if NBMiner is changing diff when such is communicated by pool during already established mining process

Talking about mining.set_difficulty command in particular

**Comment by nebutech-admin** [comment]
@pinpins set_difficulty will be affected in the next job. Won't change the difficulty of current job .

**Comment by pinpins** [comment]
yes, thanks for looking into, it appeared to be issue on my pool side.

Can be closed!
