### ISSUE TITLE
Dual mining ETH+CKB!

### ISSUE THREAD

**Issue by BARUCHER777** [NebuTech/NBMiner#135]
The hash drops very much during the dual mining of ETH + CKB currency twice the loss of hashrate on the Etherium ....
If Ethereum is mined alone, then the hash rate in the region of 51-52 .... with a dual mining of only 28 Megahashes ... in other programs, the hash rate is not so significant!
All these problems arise precisely on the AMD RADEON 5700XT video card!

**Comment by nebutech-admin** [comment]
Close due to ckb mining is nolonger profitable on GPU
