### ISSUE TITLE
Dualmining ETH+HNS fails on MiningPoolHub

### ISSUE THREAD

**Issue by RainbowMiner** [NebuTech/NBMiner#137]
Hi,

it looks like your regex checker for the dual-mining url (ETH)  has a problem. Starting dual mining with ETH pointing to MiningPoolHub, I get the following error at startup:
```
[15:42:38] ERROR - Accepted URL format in regular expression: ^(stratum|nicehash|ethproxy)\+(tcp|ssl)\://[^\:]+:[0-9]{1,5}$
```

.. this is the commandline (I have subst. my usernames/workernames with user.worker):
```
nbminer.exe -o stratum+tcp://handshake-us.6block.com:7701 -u user.worker:x -do nicehash+tcp://europe.ethash-hub.miningpoolhub.com:17020 -du user.worker:x -a hns_ethash
```

NBminer runs fine on MiningPoolHub, if mining ETH, only.

**Comment by nebutech-admin** [comment]
@RainbowMiner Is this still the case on the latest version? I cannot reproduce the error.

**Comment by RainbowMiner** [comment]
I can confirm, this works fine, now. I'll close this thread.
