### ISSUE TITLE
what is detail protocols about the mining.notify and mining.submit for HNS?

### ISSUE THREAD

**Issue by rocqina** [NebuTech/NBMiner#139]
Hi, 
method:mining.notify, params:["jobid", "prev_hash", "merkroot?", "witnessroot?", "tree_root", "reserved_root"],
method:submit, params:["worker", "jobid", "extranonce?", "time", "nonce?", "hash"]

 I am not sure the params. Can you tell me?

**Comment by nebutech-admin** [comment]
@rocqina Please contact with me in discord channel.

**Comment by kingouxy** [comment]
Hi,
method:mining.notify, params:["jobid", "prev_hash", "merkroot?", "witnessroot?", "tree_root", "reserved_root"],
method:submit, params:["worker", "jobid", "extranonce?", "time", "nonce?", "hash"]

I am not sure the params. Can you tell me?
