### ISSUE TITLE
[Question] Which coins for --coin

### ISSUE THREAD

**Issue by RainbowMiner** [NebuTech/NBMiner#141]
Hi,

which coins are allowed for the --coin parameter when mining with ethash algorithm? Is it ETH and ETC? Or are specific or all coins allowed?

Thank you for your answer in advance!

RBM

**Comment by nebutech-admin** [comment]
Currently, only mining etc is needed and effected. --coin etc
@RainbowMiner BTW, please join out discord channel in README.md, where you can get more timely responsive.
