### ISSUE TITLE
Memory Tweaker : Driver Start Failed

### ISSUE THREAD

**Issue by jgonzis** [NebuTech/NBMiner#145]
I run it in Windows with admini privileges and I get this error.

**Comment by nebutech-admin** [comment]
@jgonzis Which version of Windows are you using?

**Comment by jgonzis** [comment]
I'm using Windows 1903, NVIDIA Driver 442.53 and Adrenalin 18.6.1

I have a mix rig 1070 and 1070ti and RX570. 

B250 MINING Expert

**Comment by nebutech-admin** [comment]
Fixed in 30.2
