### ISSUE TITLE
Error Creating DAG file

### ISSUE THREAD

**Issue by iAmGrizzly** [NebuTech/NBMiner#149]
My rig has 3 RX 580 8GB GPUs and when I try to run all 3 at once I get an exception error for one of the GPUs and it restarts the miner. If I run 1 or 2 GPUs I don’t have any issue, and they all worked when I ran them individually except which ever one was the last one to be turned on. Can provide more detail if necessary.

Drivers are up to date

**Comment by nebutech-admin** [comment]
can you post a screenshot contains the startup print of system information. chances are that the virtual memory is not enough on windows

**Comment by iAmGrizzly** [comment]
Well nvm looks as if the issue solved itself. They’re working now -facepalm- restarted my PC a few times and that seemed to do the trick.
