### ISSUE TITLE
Low GPU ram usage

### ISSUE THREAD

**Issue by AronWater** [NebuTech/NBMiner#151]
I have an RTX2080TI,  nbminier detect around 10gb of free GRAM, however only 3GB is used by nbminer.

![image](https://user-images.githubusercontent.com/36737465/82025606-295df000-96c4-11ea-810a-aa9911284826.png)

And thus the hash rate is quite low, around 34Mh/s
![image](https://user-images.githubusercontent.com/36737465/82025675-3ed31a00-96c4-11ea-9e73-d7cf099214ab.png)

**Comment by nebutech-admin** [comment]
34M is a normal hashrate for 2080ti mining algorithm `kawpow`.
How much gpu memory needed for mining is determined by specific mining algorithm, higher memory occupancy do not equal higher hashrate.
