### ISSUE TITLE
Expand memory tweak to GDDR6X (RTX 3080/3090)

### ISSUE THREAD

**Issue by fynxer** [NebuTech/NBMiner#164]
Do memory tweak for GDDR6X (RTX 3080/3090), it seams nvidia is a bit restrictive with memory timings so it could be worth investigating if GDDR6X timings can be tweaked to increase performance. Seen on forums that Chinese miners got +100MH on 3080 by tweaking so it seams to be a possibility for at least 10-20% extra performance gain.

**Comment by 4iller** [comment]
NBminer not support RTX 30 serise，include RTX3070（test device）

**Comment by jgonzis** [comment]
> NBminer not support RTX 30 series，include RTX3070（test device）

It is working on my rtx 3080 without any problem... not probably 100% optimazed but it is working

**Comment by fynxer** [comment]
Mining is all about profit, more hash rate with lower power consumption equals more crypto for less money.

Optimizing by strapping GDDR6X could possibly yield another 10-20% hash rate.

You are already doing it with GDDR5X so why not try out GDDR6X optimization.

**Comment by nebutech-admin** [comment]
It's not allowed by Nvidia's driver anymore, for newer GPUs.

**Comment by ShuttleDDD** [comment]
> It's not allowed by Nvidia's driver anymore, for newer GPUs.

There is a way to do so, even adjusting the core clock is possible.

**Comment by homerobono** [comment]
GDDR6 optimization (without the X) would benefit series 20xx cards. Really hoped to see that happening!
