### ISSUE TITLE
Error connecting to europe.ethash-hub.miningpoolhub.com:20535

### ISSUE THREAD

**Issue by UselessGuru** [NebuTech/NBMiner#165]
Approx 30% of the time I get connection errors when mining Ethash @MPH on Europe server:

[MPH_Ethash_Europe.log](https://github.com/NebuTech/NBMiner/files/5328791/MPH_Ethash_Europe.log)

Asia server is fine during all my tests, e.g.:

[MPH_Ethash_Asia.log](https://github.com/NebuTech/NBMiner/files/5328790/MPH_Ethash_Asia.log)

Other miner software, e.g. PhoeninxMiner do work fine on all server @ all times.

===================================
UselessGuru: Co-developer of [http://nemosminer.com](https://github.com/Minerx117/NemosMiner/issues/71)

**Comment by jgonzis** [comment]
Only add this to the server connection line nicehash+tcp://
