### ISSUE TITLE
3080 works the same as 2080 TI

### ISSUE THREAD

**Issue by datsunondo2004** [NebuTech/NBMiner#172]
The 3080 card works the same as the 2080 TI. An approximate hash is 24-26. For 3080, 26 is the maximum. Please optimize the miner for new video cards

**Comment by datsunondo2004** [comment]
Coin CFX Conflux

**Comment by jgonzis** [comment]
> The 3080 card works the same as the 2080 TI. An approximate hash is 24-26. For 3080, 26 is the maximum. Please optimize the miner for new video cards

I'm mining at 38Mhs with a 3080 RTX...  Why you so low?

**Comment by nebutech-admin** [comment]
They have the same 68 SM units, which indicates same amount of INT ALUs, behaving similar in mining is as expected.
