### ISSUE TITLE
RX 5700 XT - Octopus - LOW hashrate

### ISSUE THREAD

**Issue by Miiichal** [NebuTech/NBMiner#174]
Unable to mine Octopus on Radeon RX 5700 XT
...
![obrazek](https://user-images.githubusercontent.com/47387162/100482049-794b5400-30f6-11eb-8806-1757a46822dd.png)

**Comment by Miiichal** [comment]
Solved in version 34.3 - support for drivers 20.11.xxx

**Comment by Miiichal** [comment]
**Octopus hashrate**
AMD RX 5700 XT - about 19.4 MH/s :(
nVidia RTX 2070 - about 42 MH/s
nVidia RTX 2070S - about 47 MH/s
nVidia RTX 2080 - about 53 MH/s
nVidia RTX 2080S - about 57 MH/s

**Comment by nebutech-admin** [comment]
@Miiichal Only Turing and Ampere GPUs have a fast implementation of a crucial instruction needed by `octopus` algo.
Every other GPUs is slow on `octopus`.

**Comment by Miiichal** [comment]
OK thank you :)
Closing...
