### ISSUE TITLE
Share rejected; Share above target on Nicehash

### ISSUE THREAD

**Issue by platinum4** [NebuTech/NBMiner#175]
All rejects

**Comment by platinum4** [comment]
![image](https://user-images.githubusercontent.com/6779241/100497423-2d61d480-3121-11eb-80ec-903f07840857.png)

**Comment by BigShoots** [comment]
Same issue on my end, had to disable octopus algorithm cause it's just wasting power.

**Comment by platinum4** [comment]
Resolved by waiting for a day
