### ISSUE TITLE
CUDA ERROR: OUT OF MEMORY

### ISSUE THREAD

**Issue by DigitalCavalry** [NebuTech/NBMiner#201]
![d8447192285e2caffc2a0833afcd371](https://user-images.githubusercontent.com/77381490/104430716-04f34400-55c2-11eb-868d-15a17b35aa09.png)

Hi, 
I'm using the 1650SUPRE graph card. It showed this error. Could you please help me to solve this problem?
THX

**Comment by DigitalCavalry** [comment]
Using WIN10 64， RAM 16G 

NBminer V36.1

**Comment by nebutech-admin** [comment]
@DigitalCavalry 4GB GPU is no longer supported to mining ETH

**Comment by vardam101** [comment]
what can i do
![Screenshot (5)](https://user-images.githubusercontent.com/129109591/228041440-1b1b2733-d72a-4511-9a04-85f8655e1da6.png)
@nebutech-admin
