### ISSUE TITLE
"Algorithm 'kawpow' is not supported on device 0: GTX 750 Ti 4GB"

### ISSUE THREAD

**Issue by andrewsobo30** [NebuTech/NBMiner#217]
Greetings,
I'm having quite a large issue and I'm hoping to receive some help. I am trying to mine RVN with NBMiner on a GTX 750 Ti. However, when I try to start mining, I receive an error message that says:

"Algorithm 'kawpow' is not supported on device 0: GTX 750 Ti 4GB"

I would greatly appreciate any help! Thank you so much!

**Comment by nebutech-admin** [comment]
only pascal (10xx series) and newer Nvidia GPUs are supported
