### ISSUE TITLE
Source Code for All Versions is Inaccessible

### ISSUE THREAD

**Issue by User777Here** [NebuTech/NBMiner#224]
When downloading the tar.gz or zip for source code, nothing is present apart from configuration files and examples. 

Can the source code be uploaded please so it can be inspected for Suspect! and NB-Miner trojan code.

Thanks

**Comment by mocmocamoc** [comment]
They won't provide the source because it'd possible to remove the code that mines their dev fee, and because they're in competition with the other miner programs.

**Comment by User777Here** [comment]
Hi Neil,

 

Thanks, appreciate it. There’s definitely some miners that include viral code as part of the installation, I found one this week that also attached a virus executable in addition to the miner (I didn’t download via github). 

 

The problem being without someone having the ability to scrutinise source code, there are no independent checks to ensure that the executable produced is not performing something it shouldn’t – ie providing a backdoor, copying filesystem data, logging key strokes and URL’s visited in an attempt to access banking software, accessing login to crypto wallet provider credentials etc etc etc. All of these could be done in a way where only an outbound connection is required etc etc. 

 

I guess the best policy is to keep mining machines segregated away from other systems and always plan that anything could be present on the mining software – in particular if an individual or group was to being purchasing out the crypto mining software one by one to reduce others ability to use non-infected programs……. 

 

Just food for thought.

 

Thanks, Chris
