### ISSUE TITLE
ARM build?

### ISSUE THREAD

**Issue by ASpieler** [NebuTech/NBMiner#226]
Feature Request: aarch64/armv8 build.
any chance of it happening?

EDIT to clarify request:
I have an aarch64 powered device running a Broadcom BCM2711 SOC, which has a PCIe 1x lane, and support for desktop graphics cards via a riser.
My request is for an aarch64/armv8 linux build to run on that device, and mine using my (otherwise currently supported) NVIDIA card.

**Comment by nebutech-admin** [comment]
No future plans for ARM build.
