### ISSUE TITLE
MUtl is not 100

### ISSUE THREAD

**Issue by 1e0ng** [NebuTech/NBMiner#227]
Hi, the column `MUtl` does it stand for Memory Utilization?

I notice one of my GPU's MUtl is not 100 while for all others it is 100.

What could be the possible cause and does it affect the actual performance?

![image](https://user-images.githubusercontent.com/1264873/108793024-8ffe2b80-75bd-11eb-856c-33e71cec95f6.png)

**Comment by nebutech-admin** [comment]
All 16 & 20 series cannot be full utilized for ETH mining because of GPU memory timings is not suitable for ETH mining and cannot be tweaked by Nvidia's limitation

**Comment by 1e0ng** [comment]
Hi, thank you for answering my question and it does make sense. What I'm still curious about is, as the screenshot shows, some 1660S cards are having 100% memory utilization...

**Comment by nebutech-admin** [comment]
@1e0ng Those '100 mutl' 1660s's, as I expected, should be using Hynix Mem chips with -500 MemClock.
When Hynix chips set to -500, that will change memory timinigs, which accidently matches ETH mining.
So at this point MUTL is 100

**Comment by 1e0ng** [comment]
Hi @nebutech-admin you are absolutely right. Thank you.
