### ISSUE TITLE
Suspicious TCP connection to 114.215.199.192 and 66.171.248.178 when the miner started.

### ISSUE THREAD

**Issue by Tengger** [NebuTech/NBMiner#228]
Any explanations for this?

**Comment by informatorius** [comment]
IP: 114.215.199.192
netname:        ALISOFT
descr:          Aliyun Computing Co., LTD
descr:          5F, Builing D, the West Lake International Plaza of S&T
descr:          No.391 Wen'er Road, Hangzhou, Zhejiang, China, 310099

IP: 66.171.248.178
Name:  ALCH-1136 
Customer:  CGP HOLDINGS, INC.
Customer Handle:  C04753118
Address:  2312 Park Ave # 105
City:  Tustin
State/Province:  CA
Postal Code:  92782
Country:  United States

**Comment by nebutech-admin** [comment]
https://bitcointalk.org/index.php?topic=5099379.msg49345024#msg49345024
explained in first page on NBMiner's BitcoinTalk thread.

**Comment by zcapr25** [comment]
even when using the socks --proxy option, both addresses are hit directly when starting the program rather than going through the proxy. could this check be modified to use the proxy? the call to 66.171.248.178 is probably fine (whatismyip) but 114.215.199.192 might look suspicious.

**Comment by nebutech-admin** [comment]
@zcapr25 ddns.oray.com
the same use as whatismyipaddress
socks5 proxy only applies to user connection to pool

**Comment by zcapr25** [comment]
i think it would make sense to proxy *all* network connects through the socks proxy if specified.
