### ISSUE TITLE
其他电脑可以使用网页监控，查看具体信息吗？

### ISSUE THREAD

**Issue by TTKCB** [NebuTech/NBMiner#229]
RT

**Comment by nebutech-admin** [comment]
没有手动指定 -api 参数的话，可以在局域网内其它电脑输入 http://矿机ip:22333 查看网页监控

**Comment by newstarting888** [comment]
> 没有手动指定 -api 参数的话，可以在局域网内其它电脑输入 [http://矿机ip:22333](http://%E7%9F%BF%E6%9C%BAip:22333) 查看网页监控

这个API里面的内容能通过启动的时候去修改让他显示哪些内容嘛？
