### ISSUE TITLE
out of memory rx580 4gb

### ISSUE THREAD

**Issue by CypherCripto** [NebuTech/NBMiner#232]
hello, I would like to know if you can edit the .bat file to use less memory to mine ETH, because using nicehash it can mine eth by decreasing the allocated memory, perhaps as in lolminer the code --4g-alloc-size 4024 - -keepfree 8 added to the .bat file, is there any code you can add to the NBminer .bat as well?

**Comment by nebutech-admin** [comment]
@CypherCripto 4GB ETH mining is not supported any more in NBMiner.
