### ISSUE TITLE
CUDA Error: out of memory (err_no=2)

### ISSUE THREAD

**Issue by ZSRock** [NebuTech/NBMiner#267]
Hi, i'm using RTX 3080 10G, the card has this problem is a new card running in +memory 700 for just 2 days, once shut down the computer and restart then this occurred, could you please help me?
![WechatIMG16](https://user-images.githubusercontent.com/41192397/114311474-7db25f80-9b21-11eb-91f2-474e382edbf7.jpeg)

**Comment by gtseriesx** [comment]
i have the same problem
![2021-05-09 23_15_40-C__Windows_system32_cmd exe](https://user-images.githubusercontent.com/34312803/117577532-b9d6e100-b11c-11eb-9450-7ade9b954796.png)
