### ISSUE TITLE
5600xt amd driver 21.4.1 - issue dag verification failed invalid --%

### ISSUE THREAD

**Issue by UnfairDead** [NebuTech/NBMiner#276]
never had any issue before updating the driver

**Comment by ShaunTheQuietGamer** [comment]
Getting the same thing on a 5700XT with 21.4.1

**Comment by roma07-unit** [comment]
Getting the same issue, never happened before with the same GPU. I thought it was my setup, I've redownloaded the pluggin which didn't fix the issue either. Glad others are also experiencing this.

**Comment by roma07-unit** [comment]
Please fix as this is making it unable to us NBMiner (which is the most efficient)

**Comment by roma07-unit** [comment]
@nebutech-admin

**Comment by nebutech-admin** [comment]
fixed in 37.2
