### ISSUE TITLE
Timing does not apply to GTX1660 graphics card

### ISSUE THREAD

**Issue by qq932480666** [NebuTech/NBMiner#283]
Timing does not apply to GTX1660 graphics card

**Comment by qq932480666** [comment]
![image](https://user-images.githubusercontent.com/69789399/115982293-7d5b9f00-a5cc-11eb-94ee-34c19af90bbb.png)

**Comment by nebutech-admin** [comment]
@qq932480666 it's supposed to not work on 16 series, as described in readme.
Nvidia not allow modify timinings for Turing and Ampere any more, and we have not found any work-around yet.
