### ISSUE TITLE
AMD 5600XT GPU issue with 37.1 version. Please update Nicehash Miner source code to 37.2

### ISSUE THREAD

**Issue by roma07-unit** [NebuTech/NBMiner#288]
DAG failure based off AMD 5600XT GPU from Ryzen software update 24.4.1 for miner version 37.1. I have manually updated to version 37.2 however NiceHash keeps reverting the pluggin to the 37.1 version. Please update the miner source code or send this 37.2 version to get automatically installed through NiceHash (currently all of the codes show 37.1 version). NBMiner is the most efficient algorithm however, I am unable to run it currently and have to use a worse alternative.

**Comment by Siftah** [comment]
I think this issue is better directed at NiceHash, not NBMiner.
