### ISSUE TITLE
8卡3060矿工经常内核重启

### ISSUE THREAD

**Issue by bbbidng** [NebuTech/NBMiner#291]
在新出的8卡3060矿机上，每天都会内核重启

**Comment by nebutech-admin** [comment]
@bbbidng 460+的驱动接口里面会有内存泄漏，3060用的470.05的话，加上`-no-health`参数关闭温度查询可解决内存泄漏问题

**Comment by bbbidng** [comment]
根据这个方法，并不能解决内核重启

发自我的iPhone
