### ISSUE TITLE
轻松矿工上最新版本反而比这边高？

### ISSUE THREAD

**Issue by zzyyzz1992** [NebuTech/NBMiner#335]
![image](https://user-images.githubusercontent.com/3894825/122823274-bb95e600-d311-11eb-8fa0-bba20c8bffd0.png)
![image](https://user-images.githubusercontent.com/3894825/122823597-26472180-d312-11eb-8673-f71672e20fe2.png)
这是啥情况？
![image](https://user-images.githubusercontent.com/3894825/122823689-41b22c80-d312-11eb-947e-76319f15bec7.png)
签名都是一家公司

**Comment by nebutech-admin** [comment]
@zzyyzz1992 这个是修复了和轻松矿工的一些兼容性，所以没有发公开版。过几天会有新版本
