### ISSUE TITLE
Power is 0 on GTX 1650

### ISSUE THREAD

**Issue by ektefa** [NebuTech/NBMiner#349]
Power is always 0 on GTX 1650
Is power embeded in source code or anything wrong with my config?

![Power](https://user-images.githubusercontent.com/16678574/124397648-6c46b100-dd26-11eb-8f77-3a5ebfe98063.jpg)

**Comment by elaaar** [comment]
Same on gtx 1070ti and gtx1080

**Comment by ektefa** [comment]
delete it please
