### ISSUE TITLE
(Hive OS) Not seeing hashrate

### ISSUE THREAD

**Issue by DejanRibnikar** [NebuTech/NBMiner#374]
I'm using HiveOS and noticed that without api argument, the miner reports hashrate to the OS correctly, but with api argument set to 0.0.0.0:port the hashrate stops being seen by OS. The miner is still working, API is showing data as supposed, but watchdog can't be used with it.

**Comment by gtdiehl** [comment]
@DejanRibnikar Did you figure out how to see the API data and have HiveOS display the hashrate?

**Comment by DejanRibnikar** [comment]
Yes, turns out if i leave the port 22333 unchanged, then it works.
