### ISSUE TITLE
Radeon RX6800XT / Ubuntu 20.04.2 not supported?

### ISSUE THREAD

**Issue by Tongie969** [NebuTech/NBMiner#392]
Hello all, 

I am trying to use NBMiner with my new Ubuntu 20.04.2 system. Doesn't matter what drivers I try ( AMD GPU Pro 21.10 l 21.20 l 21.30 and latest RocM ) NBM doesn't recognize the cards. 

glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     AMD
    GL_RENDERER:   AMD Radeon RX 6800 XT (SIENNA_CICHLID, DRM 3.41.0, 5.11.0-27-generic, LLVM 12.0.0)
    GL_VERSION:    4.6 (Compatibility Profile) Mesa 21.0.3

Is there anyway driver/Kernel setup to get NBM running with my setup or are there informations I can provide to get it running in future? 

I am willing to help as much as I can.

**Comment by kadirozgun** [comment]
Hi @Tongie969 i recently having this issue with amd radeon pro v520. Could you solve this problem?

**Comment by Tongie969** [comment]
Yes I could, you need to get kernel 5.11xxx AMD GPU pro 20.10. Install will throw out a error but it's working. 

I am with teamred miner now as I couldn't find any support here.
