### ISSUE TITLE
3060 laptop stuck at 17/18 mh/s, lhr mode doesn't work

### ISSUE THREAD

**Issue by LorenzoTinfena** [NebuTech/NBMiner#412]
it seems that it can't detect the lhr, cause in the logs there are nothing about lhr

**Comment by Sinine831** [comment]
3060 laptop>> for notebook 
it's not LHR series
See your notebook power mode ， Is the highest performance??

**Comment by LorenzoTinfena** [comment]
> 3060 laptop>> for notebook
> it's not LHR series
> See your notebook power mode ， Is the highest performance??

I will set now but there is no change, around 17 mh/s, and around 13 on t-rex miner, without oc
![image](https://user-images.githubusercontent.com/63742692/132543942-7554e93a-abe0-4263-8233-de091c4f3617.png)
