### ISSUE TITLE
100% reject

### ISSUE THREAD

**Issue by bandzula** [NebuTech/NBMiner#428]
I have 100% share reject with new Manli RTX 3060 ti. I don't know where is problem. Even factory setting (no OC) and "-lhr -1" does not help. GPU temperature is max. 65C.
INFO - etchash - #1 Share rejected: {"error":"Provided PoW solution is invalid!"}, 16 ms. [DEVICE 0, #1]

**Comment by GP-101** [comment]
Could you provide more informations about the miner's settings and your setup ? (OS, ram etc...)

**Comment by bandzula** [comment]
> 
> 
> Could you provide more informations about the miner's settings and your setup ? (OS, ram etc...)

I have i7-4790K CPU @ 4.00GHz, RAM	16 GB, Win10
Manli RTX 3060 ti, and same result with MSI GTX1070

nbminer -a etchash -o stratum+tcp://ethash.poolbinance.com:1800 -u bandxxner.gamingrig -log 

no luck wit other pool

![Rejects 2021-09-13 194354](https://user-images.githubusercontent.com/31830/133132517-a4cb238b-a87e-4ce3-be35-b66071cdc7fa.png)

**Comment by cy11100** [comment]
You do realize you're mining etchash with ethash pool?

**Comment by bandzula** [comment]
> 
> 
> Could you provide more informations about the miner's settings and your setup ? (OS, ram etc...)

I have i7-4790K CPU @ 4.00GHz, RAM	16 GB, Win10
Manli RTX 3060 ti, and same result with MSI GTX1070

nbminer -a etchash -o stratum+tcp://ethash.poolbinance.com:1800 -u bandxxner.gamingrig -log 

no luck wit other pool

![Rejects 2021-09-13 194354](https://user-images.githubusercontent.com/31830/133132517-a4cb238b-a87e-4ce3-be35-b66071cdc7fa.png)


> 
> 
> You do realize you're mining etchash with ethash pool?

NO, problem with registration.

500

Whoops, something went wrong on our servers.

**Comment by GP-101** [comment]
Be aware that **ETC**hash is not the same as **ETH**hash, not the same algo or crypto.

If you wished to mine ethereum you should correct to "nbminer -a ethash" at the beguining.

Happy mining !

**Comment by bandzula** [comment]
> 
> 
> Be aware that **ETC**hash is not the same as **ETH**hash, not the same algo or crypto.
> 
> If you wished to mine ethereum you should correct to "nbminer -a ethash" at the beguining.
> 
> Happy mining !

😫 but... 😌
You are a very watchful reader. I checked it about 10 times. 

Thanks.
