### ISSUE TITLE
Is it normal behavior?

### ISSUE THREAD

**Issue by GraverErmitage** [NebuTech/NBMiner#557]
Hi guys,

Please have a look on two red lines. I am not sure that it is normal behavior. Could you please check.
![nb396](https://user-images.githubusercontent.com/34091165/139323132-b6b556bb-b1a2-49c4-99d7-7fd7a70d2900.png)

**Comment by GraverErmitage** [comment]
I am asking why it is 8557ms and 5569ms. Not about 500 and not about 1000, but more 5 sec and more 8 sec.

**Comment by GraverErmitage** [comment]
> yes. share rejection is normal. but you need to check your internet connection if the rejected shares are more than like 2%. (it need to be as low as possible. bad internet is the main reason for share rejection.

I am asking why it is 8557ms and 5569ms. Not about 500 and not about 1000, but more 5 sec and more 8 sec.

**Comment by tsumurijp** [comment]
It's normal to get a few rejections. It's normal behavior so please close this case for allow nbminer developer to focus on other issues
