### ISSUE TITLE
-d parameter not working. DAG – verification failed, invalid x% mining with amd and nvdia lhr gpus

### ISSUE THREAD

**Issue by nmolanog** [NebuTech/NBMiner#561]
I am trying to use the new release of the nbminer with a 6600xt and a 3080ti.
I am getting the error DAG – verification failed, invalid x% for the 6600xt. I must mention that this gpu works just fine with teamredminer, so it is not and OC issue. The 6600xt works but is getting a lot of rejected shares (again this is not happening in other software.)

Since the 6600xt is failing, I am trying to run just the 3080ti (device 1) with the command:
nbminer -a ethash -o ethproxy+tcp:zzzz -u xxxx -d 1 -log -lhr-mode 1
but the miner is still using both gpus. I have tried to put the parameter -d 1 in different places in the code with the same results.

![image](https://user-images.githubusercontent.com/25943133/139355711-8f7db3c6-6c87-490a-ae35-d3171f8719b8.png)
![image](https://user-images.githubusercontent.com/25943133/139355752-41678f6d-4d99-4d51-ab40-c2e6809c306f.png)

**Comment by nmolanog** [comment]
me bad, running fine now

**Comment by xrtw** [comment]
oc settings?

**Comment by nmolanog** [comment]
> oc settings?

yes, did not know that some good OC in one miner (trm) could not work in another.

**Comment by xrtw** [comment]
> > oc settings?
> 
> yes, did not know that some good OC in one miner (trm) could not work in another.

i see your nice OC settings in 3080ti, can you share?
