### ISSUE TITLE
Download link 

### ISSUE THREAD

**Issue by ImpliedConsent** [NebuTech/NBMiner#576]
https://github.com/NebuTech/NBMiner/releases/download/v39.7/NBMiner_39.7_Win.zip

That download link is failing.

![Screenshot 2021-11-01 095621](https://user-images.githubusercontent.com/29551816/139702127-65590e85-ae86-433c-9f56-608aaf12c3d6.jpg)

**Comment by xrtw** [comment]
disable anti virus

**Comment by ImpliedConsent** [comment]
> disable anti virus

I'm an idiot ... disregard anything I might ever say again. /smmfh
