### ISSUE TITLE
Request: Addition of Equihash 125,4 Algorithm

### ISSUE THREAD

**Issue by gorgarp** [NebuTech/NBMiner#577]
Hello! I'd like to request Equihash 125,4 be added. Our project, Flux (Runonflux.io), is a GPU minable coin and is one of the fastest growing projects in the space.

Please reach out to us on dicord.io/runonflux, if you would like to discuss this. Your project looks extremely promising and we'd love to work with you.

Current implementations are gminer, miniz, lolminer.

**Comment by fmarindu** [comment]
I'm totally agree
