### ISSUE TITLE
Hiveos LOW current hashrate lower than reported vs Average in ethermine pool please help how fix this.. see this screenshot!!!

### ISSUE THREAD

**Issue by ROCKET0101** [NebuTech/NBMiner#584]
![Capture](https://user-images.githubusercontent.com/92781808/139824193-d245f836-d4f8-49fd-89fb-3df72b199a58.PNG)
![Captureas](https://user-images.githubusercontent.com/92781808/139824489-6d8d3c35-9a95-4474-b4e2-70b344b70742.PNG)

**Comment by mtmtmt123** [comment]
you have to wait hours
