### ISSUE TITLE
Bro my rig is working properly but in hive os show offline some time show data loading retry.. and i am using nbminer that time i do not know but is this .please help bro!!!!

### ISSUE THREAD

**Issue by ROCKET0101** [NebuTech/NBMiner#587]
![Screenshot 2021-11-03 175121](https://user-images.githubusercontent.com/92781808/140061957-7b6fb7fb-35a5-4bff-87b9-a2203c10fbbb.png)

**Comment by dedizones** [comment]
Why write problem title nub !


see log miner or rig and post on hiveos forum

**Comment by pdieppa** [comment]
Looks like HiveOn was having some issues with their API servers.  I think they are back online now.

**Comment by ROCKET0101** [comment]
> Looks like HiveOn was having some issues with their API servers.  I think they are back online now.

Yes bro some time hive os can't run properly.
