### ISSUE TITLE
3090 Asus 

### ISSUE THREAD

**Issue by HenriquePereiraRosa** [NebuTech/NBMiner#637]

**Comment by HenriquePereiraRosa** [comment]
![image](https://user-images.githubusercontent.com/16025104/142518859-81d39c78-a565-4e6b-855c-9f9d980ac193.png)

![image](https://user-images.githubusercontent.com/16025104/142518934-b0da3b54-5407-4796-b917-bc1d7b2cff86.png)

**Comment by Jukeyz** [comment]
For me I doubled checked my ventilation if you are using It in a case. If being used in rig maybe make sure ambient room temp is not hot or over 24c because that affects the overall temps by a lot. Good luck.

**Comment by HenriquePereiraRosa** [comment]
delete it please.
