### ISSUE TITLE
请问40.0多块GPU怎么设置

### ISSUE THREAD

**Issue by xsyl520** [NebuTech/NBMiner#654]
-d 0,1,2,3,4 -pl 
怎么对每一块卡单独设置功耗，核心，显存等参数？格式是什么？

**Comment by IordX** [comment]
will be nice to know , if rig have different GPUs and need to set OC per each GPU
both AMD and NVIDIA supported ?

**Comment by lbf4616** [comment]
同问

**Comment by samljh** [comment]
nbminer -a ethash --proxy 127.0.0.1:10808 -o ethproxy+ssl://asia2.ethermine.org:5555 -u 0x295337xxxxxx.xxx --devices 0 1 2 3 -pl 85% 85% 76% 76% -cclock @1200 @1200 @1200 @1200 -mclock 1350 1350 1350 1350
失败，系统只认出第一张卡
failed,just first GUP working

**Comment by nebutech-admin** [comment]
所有可单独设置的参数，都是用逗号分隔，比如
-cclock @1200,@1300,200,@2000 -d 0,1,2,3
