### ISSUE TITLE
nbdrv64.sys in system32/drivers folder

### ISSUE THREAD

**Issue by arinyaho** [NebuTech/NBMiner#663]
Windows defender classifies it as PUA WIN32 ClickAthlete. 
Is this file expected?

**Comment by adfaklsdjf** [comment]
If this were in NBMiner's own folder, rather than system32/drivers, I would find it less concerning...

**Comment by Alanimus** [comment]
I'm having this issue too, windows picks it up as a virus clickathlete

**Comment by jacksterz** [comment]
I also received a Windows Defender alert about this today, been using the same nbminer version for over a month now and this is the first time that I got this alert.

**Comment by TuXEKRO** [comment]
I just got the same notice

PUA:Win32/ClickAthlete

**Comment by Theoisx** [comment]
I got this to day and let Microsoft Defender take care of it. Didn't affect my mining. I had experience some strange behavior while gaming yesterday. Screens would pop-up in the middle of the game. Hope it's gone now

**Comment by Theoisx** [comment]
I got it too. After Windows Defender removed it and 2 reboots, NBMiner failed to work.

**Comment by mdengler** [comment]
Why is this closed as completed?  This is still occurring, AFAICS.

**Comment by nebutech-admin** [comment]
It's a custom driver for memory tweak GDDR5 & 5X on windows.
It's now not required anymore on v42.x version.
