### ISSUE TITLE
parameter proxy cannot help my dns get proxied(Chinese: proxy 参数无法代理DNS服务)

### ISSUE THREAD

**Issue by linlexuan2005** [NebuTech/NBMiner#668]
Due to China mainland network operation policy, we cannot resolve pool IP address throuth any DNS server. So I set proxy parameter linked my socks5 proxy nbminer, however miner still cannot resolve the pool url's real IP address . I wonder maybe this parameter cannot get my dns service proxied so that the url resolving stage still operated locally. I'm not sure my guess is right, if I'm right plz add dns proxy to miner, maybe support socks5h or whatever, that will help a lot China miners, thanks so much!

Chinese version if there is Chinese developer:

由于中国大陆网络运营商政策，我们无法通过任何DNS服务器正确解析矿池地址。我使用proxy参数将nbminer代理到我的socks5代理服务上，仍然无法解析正确的矿池IP。我怀疑proxy这个参数也无法帮助软件通过代理解析正确的地址，即使配置这个参数还是使用国内的dns服务进行解析。我不知道这个猜想是否正确，如果是正确的，能否修将dns代理也加入进去，比如说支持socks5h协议等方法，十分感谢！

**Comment by liukaixin007** [comment]
老铁，这个代理nbminer软件具体怎么配啊，还需要些写矿池地址吗？比如我的代理服务器ip是192.168.1.100 端口1080，麻烦老铁写个配置例子！多谢！

**Comment by liukaixin007** [comment]
这是我目前的 nbminer -a ethash -o ethproxy+ssl://cdn.ethcage.vip:49258 -u 0xe75c1fb07349285c722c781ba85b1d0d77113244.test

**Comment by linlexuan2005** [comment]
> 这是我目前的 nbminer -a ethash -o ethproxy+ssl://cdn.ethcage.vip:49258 -u 0xe75c1fb07349285c722c781ba85b1d0d77113244.test

nbminer -a ethash -proxy 192.168.1.100:1080 -o ethproxy+ssl://cdn.ethcage.vip:49258 -u 0xe75c1fb07349285c722c781ba85b1d0d77113244.test

**Comment by u373693041** [comment]
--proxy 127.0.0.1:1080
就是--proxy加你的代理地址加端口号

**Comment by sistinafibe** [comment]
> > 这是我目前的 nbminer -a ethash -o ethproxy+ssl://cdn.ethcage.vip:49258 -u 0xe75c1fb07349285c722c781ba85b1d0d77113244.test
> 
> nbminer -a ethash -proxy 192.168.1.100:1080 -o ethproxy+ssl://cdn.ethcage.vip:49258 -u 0xe75c1fb07349285c722c781ba85b1d0d77113244.test

成功了吗老铁

**Comment by liukaixin007** [comment]
非常感谢！
