### ISSUE TITLE
How to kill NBMiner process in Linux

### ISSUE THREAD

**Issue by Pangjing-Wu** [NebuTech/NBMiner#679]
I try to kill the miner process by `kill -9 <pid>`, but the miner restart after a few seconds.
I'd like to know how to kill it, should I set some arguments to avoid it restart, just like the `-mode` argument in PhoenixMiner.

**Comment by kadimakipp** [comment]
ps -aux |grep nbminer
find watchdog processes and kill them

**Comment by kadimakipp** [comment]
you can use `--no-watchdog`  to Disable watchdog process.

**Comment by Pangjing-Wu** [comment]
> 

Thanks a lot, it's very useful
