### ISSUE TITLE
Mining ergo - ailed to establish connection to mining pool: Connection refused

### ISSUE THREAD

**Issue by devcao** [NebuTech/NBMiner#680]
ergo - Logging in to us.ergo.herominers.com(51.81.155.46):1180 ...
[21:55:08] ERROR - ergo - Failed to establish connection to mining pool: Connection refused
[21:55:08] INFO - Logout.

How to fix this?

**Comment by ROCKET0101** [comment]
> ergo - Logging in to us.ergo.herominers.com(51.81.155.46):1180 ...
> [21:55:08] ERROR - ergo - Failed to establish connection to mining pool: Connection refused
> [21:55:08] INFO - Logout.
> 
> How to fix this? 

Same issue in ethereum

**Comment by devcao** [comment]
Seems fixed now, will close this.
