### ISSUE TITLE
bro why this power drop sum time any bady help me!! see this pic....

### ISSUE THREAD

**Issue by ROCKET0101** [NebuTech/NBMiner#685]
![Screenshot 2021-12-01 193040](https://user-images.githubusercontent.com/92781808/144247881-204f1a64-a4ed-46c2-ae04-ece7ff092c86.png)

**Comment by pdieppa** [comment]
Sorry but you have not provided enough information for anyone to be able to help you.

**Comment by ROCKET0101** [comment]
> Sorry but you have not provided enough information for anyone to be able to help you.

Bro tell me what information give to you about this issue
