### ISSUE TITLE
DAG Verification failed after overclocking GPU

### ISSUE THREAD

**Issue by Pavich7** [NebuTech/NBMiner#700]
Only happen when overclocking the GPU before starting NBMiner.
Image: https://i.imgur.com/CY9UI5u.png

**Comment by Pavich7** [comment]
If DAG verification passed after sometimes the miner will crash.

**Comment by pdieppa** [comment]
The clock is way too high. Bring it down to 1425 instead of 1927.

**Comment by Pavich7** [comment]
Ok I will try it.
