### ISSUE TITLE
CoreClock or LockedCoreClock error, not supported!

### ISSUE THREAD

**Issue by RsZoli** [NebuTech/NBMiner#712]
Dear Friends!

I'm trying to downclock my 1060, using a json config file, but with no luck, seting either "cclock": "-400", or "cclock": "@1500", but it always seems not supported!

Of course, i'm trying to do this on Windows, any help would be much appreciated!

![dc](https://user-images.githubusercontent.com/28480037/146677684-b8992992-a450-4ba6-93b1-8c4e2bed370d.jpg)

Thank you very much!

**Comment by team-community** [comment]
The same on 1080 ti, driver 472.12

**Comment by fmarindu** [comment]
I believe that the error is with Nvidia series 1000, I have the same problem with a gtx 1070.

**Comment by JThompson101** [comment]
I am also having this same issue with a 1080ti, any know solution?

**Comment by Tom5051** [comment]
only works with 20 series or newer.
