### ISSUE TITLE
升级驱动程序后，报错，经常蓝屏

### ISSUE THREAD

**Issue by LongLifeLove** [NebuTech/NBMiner#72]
![default](https://user-images.githubusercontent.com/38159156/46054852-ad740480-c17b-11e8-9178-24bc3225bf4b.png)
![1](https://user-images.githubusercontent.com/38159156/46054860-b4027c00-c17b-11e8-8198-f92e919b75f3.png)
GTX 1060 3G，升级驱动程序后，运行BTMiner 9.0，其中显示 “Fail to initialize NVML: Unknown Error”
但好像并不影响挖矿。
随后停止挖矿，结束程序后，基本上均会蓝屏报错（大概10次中有6-7次）。如何解决，谢谢！

**Comment by stzcze** [comment]
Cuda 10... not compatible
