### ISSUE TITLE
strange hashrate overflow bug

### ISSUE THREAD

**Issue by melody2012** [NebuTech/NBMiner#73]
As image below...

![bug](https://user-images.githubusercontent.com/3454151/46590582-00887880-cae7-11e8-95df-ee40bcd9c9c6.png)

**Comment by nebutech-admin** [comment]
It is strange, never saw this happen. 

What's your driver version?

**Comment by melody2012** [comment]
> It is strange, never saw this happen.
> 
> What's your driver version?

I use driver 398.26 with CUDA 9.2
