### ISSUE TITLE
Dev fee security link problem

### ISSUE THREAD

**Issue by Kterryo** [NebuTech/NBMiner#739]
Because mining is prohibited in China, I use a custom TCP encryption software to connect to the personal server in Hong Kong and forward it to the mining pool. In this process, I specify the connection port of Nb software. Now there is a problem that I use a custom software to encrypt the mining traffic, Is the flow of this software development fee through the encrypted channel of my custom software or has another port been opened to connect to the mine pool? I'm afraid that the traffic extracted from the development fee will cause the communication operator to shut down my network. I want the development cost to connect from my custom TCP encrypted channel to the mine pool. I use SSL connection.
PS: many people around me are afraid that the development fee connection will lead to network shutdown, so they intercept the development fee, but I gave the development fee. Because I have not been informed of the disconnection, but I hope to take safety measures before being notified. Please respond quickly.

**Comment by Tom5051** [comment]
set -fee 0  but your hash rates will be lower as a result. Also you could use a packet sniffing app like wireshark to see what ports are being opened to what ips.

**Comment by Kterryo** [comment]
这不是我想要的回答，设置 -fee 0减少了10%的哈希率。我想说的是我如果用IP加端口的形式（例如154.38.14.20:5555）的形式挖ETH的话开发费能不能走154.38.14.20:5555这个地址和端口，还是另外有IP作为开发费地址？

**Comment by tsumurijp** [comment]
Set fee to 0% and If you like it, don't forget to send fee directly to developer

**Comment by Kterryo** [comment]
找到解决方案了，直接全局中转new.nebu.ltd就加密开发费用了
