### ISSUE TITLE
Help in rx 6600 xt problem 

### ISSUE THREAD

**Issue by Abdulrahmanxd** [NebuTech/NBMiner#752]
I have this issue when i mine eth in nb miner with 6 rx 6600 xt sapphire pluse 
 Can any one help or solution for this problem?? 
 
![684F382E-6796-42D3-B667-8030AE0F2671](https://user-images.githubusercontent.com/98521890/151335299-24abf620-504a-405b-966c-a2f0f6dd5c89.jpeg)

![A3C19241-7170-4C96-92B6-AA4E304AA319](https://user-images.githubusercontent.com/98521890/151335358-cbb40058-c459-4707-a6cc-196183e5eff3.jpeg)

**Comment by mininggago** [comment]
I hat similar problem and I finally change the miner...

**Comment by Abdulrahmanxd** [comment]
> I hat similar problem and I finally change the miner...

Thanks for reply what the name of miner you use ?  After this problem

**Comment by theekshanak** [comment]
> > I hat similar problem and I finally change the miner...
> 
> Thanks for reply what the name of miner you use ? After this problem

I had the same issue with nbminer, currently, I'm using lolminer and had no issues so far

**Comment by Abdulrahmanxd** [comment]
I found this solution is good for me 

*First I install the Microsoft Visual C++ 
From this link 
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-160

then I change the miner to gminer 2.75  then i add more gpu rx 6600 xt in same rig now its 10 gpu more then 1 day stable 

I hope if some one have same issues this solve for him 

thanks all
