### ISSUE TITLE
diff setting from stratum not work at miner

### ISSUE THREAD

**Issue by AlexSpain** [NebuTech/NBMiner#78]
if stratum have diff 1000, miner trying to send lower diff shares.
and spam red message about low diff

**Comment by nebutech-admin** [comment]
@AlexSpain Yes, the currenty miner do not take on the Grin Difficulty Check feature.

The reason for this is on early days of Grin mining, mining pools do not have a united definition mining difficulty, which will cause a even more trouble if miner do check difficulty.

I checked several pool just now, they seems to unit the definition.

The problem will be solved in next version.
