### ISSUE TITLE
New jobs not accepted....

### ISSUE THREAD

**Issue by bladedoyle** [NebuTech/NBMiner#83]
New "job" requests from the stratum server are not being accepted by nbminer if they have the same "job_id" as the previous job....even if the job "height" is higher than the previous job request.

The miner should consider *both* the job height and the job_id.   The job_id is a versioning of the job at a specific height.   So height=123 job_id=0  is a different job than height=124 job_id=0.

I am able to work around this bug by sending 2 job requests in a row, one with the old job height and a new job_id, followed immediately by the new job with the new job height and job_id=0, but it would be better not to have to do that.

Note:  nicehash might be using nbminer because they have exactly the same issue.

**Comment by bladedoyle** [comment]
```
[2019-02-15 14:29:42,265] INFO - cuckaroo - New job from stratum.mwgrinpool.com, ID: 999, DIFF: 1.00
[2019-02-15 14:29:42,265] INFO - cuckaroo - New job from stratum.mwgrinpool.com, ID: 0, DIFF: 1.00
```

**Comment by nebutech-admin** [comment]
Thanks for submit this issue.

Will be fixed in next version.
