### ISSUE TITLE
Too many connections, too many logins

### ISSUE THREAD

**Issue by bladedoyle** [NebuTech/NBMiner#85]
It looks like nbminer creates a separate stratum connection for each device?    Thats a lot of connections, and a lot of extra login requests for a pool to need to handle.    It might be better to use a single connection and submit / recv all messages through that.

Or, maybe you have a good reason for doing that?    Maybe the share submit performance is better when you use more connections?    If thats the case, then please let me know and also feel free to close this issue.   Im only asking for a change if the current behavior is unnecessary.

**Comment by bladedoyle** [comment]
Now that I think more about it, I think its not really a bad idea to make multiple connections for rigs with many GPU.  For a pool with multiple stratum instance, multiple connections will be load-balanced across them, and distribute the load.

I'll close this issue.

**Comment by nebutech-admin** [comment]
@bladedoyle It's really not the case.

As I mentioned in [BitcoinTalk thread](https://bitcointalk.org/index.php?topic=5099379.msg49345024#msg49345024), the connections other than user stratum, are used for some extra purposes, which are once only http get requests.
