### ISSUE TITLE
How to add backup pool in NBMiner? 

### ISSUE THREAD

**Issue by rgzrgz** [NebuTech/NBMiner#86]
Hello.
How to add backup pool in NBMiner?

Dear devs, 
I really look forward to the function of the failover pool in pools.txt file! 

Command line arguments must be always override the default JSON configuration. (config.json file)
So, .but file must be priority over the json configuration. 
while failover pools must be work in separate txt file.

Fairly common practice in the mining software development. 
Standardization with respect to the quality and usability are very good
We (a group of miners) would like to use your program, but it is not convenient.

**Comment by nebutech-admin** [comment]
-u1 -o1 for backup pool and username, -u2 -o2 for another backup pool and username
