### ISSUE TITLE
Hashrate is low as 97MH/s for 3060TI LHR

### ISSUE THREAD

**Issue by rmiragane** [NebuTech/NBMiner#860]
Please let me know what will be issue here,

I have posted images below of hashrate and my overclock settings as a reference.

![image](https://user-images.githubusercontent.com/105303676/167666845-4ba725d3-1318-44a9-ab98-e863d83d2e8b.png)

![image](https://user-images.githubusercontent.com/105303676/167666944-7ecd9cdf-0b9e-40b8-9111-bef64318b8e5.png)

**Comment by TeeCeeCrypto** [comment]
Are you using the recommended Nvidia drivers? Would be 512.15 on Windows.

**Comment by rmiragane** [comment]
yes

![image](https://user-images.githubusercontent.com/105303676/167668944-fff227be-c769-47fb-bef6-7486223ead7d.png)

**Comment by Gkozd** [comment]
Cut the power to 120-125 W per g-card and report.

**Comment by lastover26** [comment]
lock your cclk

**Comment by Tom5051** [comment]
turn off windows hardware-accelerated GPU scheduling. That is why your CPU is at 100%

**Comment by shenshen2105** [comment]
same issue like me...using 40.1 my 3060 ti LHR speed 43 when using 41.0 /3 my hash only 34-35

**Comment by rmiragane** [comment]
> turn off windows hardware-accelerated GPU

its off

![image](https://user-images.githubusercontent.com/105303676/167808054-d372ad99-9e4d-4574-9945-d1fa5050f8b1.png)

**Comment by rmiragane** [comment]
> lock your cclk

locked at 780

![image](https://user-images.githubusercontent.com/105303676/167808322-2da9b541-78c1-406e-adb0-279bb3c02656.png)

**Comment by rmiragane** [comment]
> maybe a hint, your cpu is at 100%usage. are you doing something else beside mining ? are you starting nbminer as admin ?

no i have **not started** the nb miner as admin, 

I have single login that is admin,

how to reduce the cpu usage??

**Comment by rmiragane** [comment]
with T-Rex this is the hashrate but with NB its 97MH/S

![image](https://user-images.githubusercontent.com/105303676/167809181-3d9acddf-75ff-4b70-b36a-efbff4e4259a.png)

**Comment by shenshen2105** [comment]
Not working

Pada tanggal Rab, 11 Mei 2022 15.48, rmiragane ***@***.***>
menulis:

**Comment by rmiragane** [comment]
Thanks a lot all of you, its working now.

Please check the hash rate and let me knw whether its fine or shud i have to do any changes to improve it better.

![image](https://user-images.githubusercontent.com/105303676/167818458-639cd164-eda5-43fb-959f-4cd059207895.png)

**Comment by dimitriovic** [comment]
great ! just for the sake of other users, what was the issue and fix ?

**Comment by rmiragane** [comment]
No idea, have locked the CClock and got the result,

These are the parameters that i have set

![image](https://user-images.githubusercontent.com/105303676/167821760-624dbf97-720f-4a9c-a6ec-c8e6c38f421e.png)

**Comment by dimitriovic** [comment]
maybe did you run it with admin privileges ? 
anyway that's cool for you, now enjoy juicy hashrates :)
about cpu usage at 100%, first try to investigate in task manager what is using your cpu. shouldn't be using 100%.

**Comment by rmiragane** [comment]
i dont knw why its 100%, how much it shud be??

I am using this system for below tasks apart from mining.

![image](https://user-images.githubusercontent.com/105303676/167822729-f4ab87df-ba06-46c6-a0f9-769e16ad8647.png)

**Comment by dimitriovic** [comment]
here it is ! this is because you are mining XMR with your cpu

**Comment by rmiragane** [comment]
![image](https://user-images.githubusercontent.com/105303676/167833280-965f3acc-7c1d-4a17-901f-3e95ccc31366.png)

After closing XMR, thanks a lot dimitriovic
