### ISSUE TITLE
Power being limited by driver?

### ISSUE THREAD

**Issue by rafaelfalcao** [NebuTech/NBMiner#869]
![image](https://user-images.githubusercontent.com/17484477/167961733-408dc2b3-ae78-4046-85f9-5a6b26d4e1f3.png)
This started to happen when i installed the 512.15 driver . Afterburner is set to 100% PL but nbminer only gets 84-88w which is around 65% i think. this lowers the hashrate. Any idea why?
It is not limited on the file, even if i set the pl to 100% on the bat it doesn't work.

**Comment by rafaelfalcao** [comment]
It is not being limited by the .bat file

**Comment by pdieppa** [comment]
Have you tried increasing the clock to see if that has any effect?

**Comment by zulu1905** [comment]
you can try with --cclock -320  in a bat file . it works for me at some cards

**Comment by rafaelfalcao** [comment]
Yes, this seems related to cclock. As we can see on nbminer the cclock is super low on 780 when it should be by default around 1500.
A restart on the machine seems to solve it, been mining on stable 46-47Mhs for 12h now. But its weird that the cclock is changed - i havent forced it yet on the bat file, will test this later. Thanks everyone
