### ISSUE TITLE
[FEATURE] --device-info command adjustments

### ISSUE THREAD

**Issue by S74nk0** [NebuTech/NBMiner#89]
Hello,

I have a feature request regarding the `--device-info    Print device cuda information.`. 
1.)
It seems that the current implementation prints out to `std::err` instead of `std::out` so piping out info is empty e.g. `nbminer.exe --device-info > out.txt` the out.txt will be empty. Can you please make it print to `std::out`?
2.)
I would ask if you could add PCI Bus IDs in the printout. This would come in handy with cross referencing devices e.g. inside NiceHashMinerLegacy we would cross reference **NBMiner** IDs/indexes with NiceHashMinerLegacy detected devices.
3.)
Since this feature request is for NiceHashMinerLegacy and device information will be parsed in the program, maybe an additional flag where the printout would be in easy to parse format like JSON would come in handy. Maybe `--device-info-json` would print out the information in JSON format.

Hope this would be doable in one of your next releases.
Best Regards!

**Comment by nebutech-admin** [comment]
@S74nk0 Thanks for reaching out.

Sure, these fair requirements will be fulfilled in the next version, hopefully a couple of days.

1) Change device information print to `stdout`.
2) Add `pci_id` print in device information.
3) Add an option to print json format of device information.

**Comment by nebutech-admin** [comment]
@S74nk0 Do you need all of these 3 IDs? If so, What's your prefer order or format to line them up?
![image](https://user-images.githubusercontent.com/39877212/56074826-7699cf00-5deb-11e9-9278-b4ba5ca8b268.png)

**Comment by nebutech-admin** [comment]
Close for now.
Will be added in the next version.

**Comment by S74nk0** [comment]
Sorry for late reply.
Yes `pciBusID` (https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaDeviceProp.html#structcudaDeviceProp_1c5adc2ef8c6b89fb139b4684175db54a), this is what we need (others we don't need).

Thanks.

**Comment by nebutech-admin** [comment]
@S74nk0 Fulfilled in v22.2
