### ISSUE TITLE
Super high CPU usage

### ISSUE THREAD

**Issue by GhostShot3** [NebuTech/NBMiner#919]
CPU is hitting 100% (I5-6500) on Task Manager when i start mining (w10)
nbminer -a ethash -o stratum+tcp://eth-br.flexpool.io:4444 -u 0x0e459Ae318e654737ACD01c5588c4e2E52113c0A.NBMiner1 -log --memory-tweak 6 --no-health
![4444](https://user-images.githubusercontent.com/18537420/177069264-92c7044a-e18b-4d92-b4cb-8a61a6946ec4.png)

**Comment by UHeinz13** [comment]
If you're using Windows 11 and a driver from Nvidia greater than version 466.77 then you'll get this higher CPU usage issue!

The only way to fix it then is to downgrade to the 466.77 driver or lower, or use Windows 10!

That is my experience.

**Comment by GhostShot3** [comment]
I use w10

**Comment by GhostShot3** [comment]
I tryed driver 466.77 worked but i need higher version bc RTX A2000 is not recognized with only the 466.77.

**Comment by AndrewScorpio** [comment]
You need to disable hardware accelerated GPU scheduling. In my case it was helpful

Follow these steps to turn off GPU hardware scheduling:
    Click Start, then head to Settings > System.
    From the left-hand menu, select Display.
    Below Multiple Displays, click Graphics settings.
    Turn off the toggle for Hardware-accelerated GPU scheduling.
    Restart your computer.

**Comment by GhostShot3** [comment]
It worked the CPU dropped to <10%, thanks!
