### ISSUE TITLE
a little paranoid

### ISSUE THREAD

**Issue by ddobreff** [NebuTech/NBMiner#92]
> │[2019-05-20 20:11:09][info][miner]: Sorry, this application cannot run under a Virtual Machine.                                                                                                                                            │

Hello developer[s]. I am using virtual machine with vfio and forwarding my dev GPU[P106-100] to perform tests and future integrations for our system. Can you please remove this restriction?

**Comment by nebutech-admin** [comment]
@ddobreff Thanks for reaching out.

The restriction comes from the protecting shell software.

We tend not to remove this restriction due to code security concern.

**Comment by gsxryan** [comment]
Can you elaborate on the security concern?  Perhaps we can help find a way to mitigate without blocking VM access.  I'm using PCI passthrough to a VM as well, as the resources are better utilized virtually.
