### ISSUE TITLE
NiceHash compatibility with cuckatoo31

### ISSUE THREAD

**Issue by luc1an24** [NebuTech/NBMiner#93]
Hi

With the new release of NiceHash Miner packing NBMiner 23.2 the cuckatoo31 algorithm has some problems. Sometimes it doesn't submit any share, sometimes rejects all shares and sometimes accepts all shares.

Could you look into this issue?

Thank you!

**Comment by nebutech-admin** [comment]
@luc1an24 Could you email me a log file containing what you described above?

Add '-log' to the command arguments, and a log file will be generated in logs/log_timestamp.txt.

```cmd
nbminer.exe -a cuckatoo31 -o xxx -u xxx -log
```

nebutech@hotmail.com

**Comment by luc1an24** [comment]
@nebutech-admin thank you for reply.
The log was sent to your email

**Comment by nebutech-admin** [comment]
@luc1an24 Hi, could you run the miner for a bit more time?

The very likely reason for your situation, is the high difficulty mining cuckatoo31 on nicehash.

The expected time to find a cuckoo|cuckaroo|cuckatoo share, is calculated as:

eTime = 42 * diff / hashrate

So, in your case, eTime = 42 * 8 / 1.4 = 240 secs.

It's pretty normal to me that the miner, which only using one 1080ti, do not submit in several or even 10 minutes.

If you still have doubts, run miner for over an hour and post the log, I'll see what I can do.

**Comment by luc1an24** [comment]
Thank you for your explanation. After some time (10-15 mins) I actually did got first accepted share.
Now we can close this issue
