### ISSUE TITLE
Random SSL traffic captured going to new.nebu.ltd

### ISSUE THREAD

**Issue by dontcrash** [NebuTech/NBMiner#933]
Please explain what this is?
I am assuming either some C&C or telemetry.

It originates from NBMiner.

**Comment by dontcrash** [comment]
DIG on the domain:
SOA - ns1.huaweicloud-dns.org al***@**uge.***.com 1 7200 900 1209600 300
A record 47.243.239.65

I have redacted an email address, even though it is public information and anyone can find it, I am not sure if it is intentional.

**Comment by nebutech-admin** [comment]
@dontcrash domain of devfee server.
