### ISSUE TITLE
Request: Addition of Equihash 125,4 Algorithm

### ISSUE THREAD

**Issue by gorgarp** [NebuTech/NBMiner#938]
Hello! I'd like to request Equihash 125,4 be added. Our project, Flux (Runonflux.io), is a GPU minable coin and is one of the fastest growing projects in the space. Additionally, we are considered one of the main 4 likely replacements for ETH hashrate, post merge.

Please reach out to us on dicord.io/runonflux, if you would like to discuss this. We know that your group can make a large impact and we'd love to work with you.

Current implementations are gminer, miniz, lolminer.

**Comment by WaffleBears** [comment]
Just bumping. BZminer will be adding 125,4 in the very near future as well.
