### ISSUE TITLE
Single algorithm mining intensity

### ISSUE THREAD

**Issue by NadirTennci** [NebuTech/NBMiner#96]
hi, how do I set the intensity when mining single algorithm? I'm not talking about dual mining with -di command

**Comment by nebutech-admin** [comment]
@NadirTennci 

If you encountered with high CPU usage when mining Grin or AE, you can try --cuckoo-intensity option with larger value to tune down CPU usage. 

In other cases, you do not need to set intensity.

**Comment by NadirTennci** [comment]
I wanna set a limit on intensity regardless of what algo I'm mining, it makes the computer usable, is there a way to do that? maybe in future updates?

**Comment by nebutech-admin** [comment]
@NadirTennci Got your point. Put in future plans.

**Comment by nebutech-admin** [comment]
Implemented in v24.0.
