### ISSUE TITLE
Disable power monitoring

### ISSUE THREAD

**Issue by AndMetal** [NebuTech/NBMiner#97]
Is it possible to disable power monitoring in the miner, similar to the --pec option of Gminer? The goal would be to reduce CPU overhead on weaker processors (Celeron, Pentium) without sacrificing hashrate.

**Comment by nebutech-admin** [comment]
@AndMetal Thanks for the advice. Will consider add this option in future version.

**Comment by nebutech-admin** [comment]
Implemented in v24.0.

**Comment by AlexSpain** [comment]
How? What command?
