### ISSUE TITLE
Every fifth gpu dies after the miner is terminated

### ISSUE THREAD

**Issue by spacetrain** [NebuTech/NBMiner#98]
Hello, I really appreciate for your effort to develop this great miner.
Whenever I killed the miner with ctrl+c, my fifth (id 4) and tenth (id 9) gpus from my severs (one is 10x 1080 ti on ubuntu 16.04 and the other one is 10x 1080 ti on ubuntu 18.04) die and have to reboot to use them.
I can confirm they are in error state with nvidia-smi.
When the gpus dead I tried to reload them with several ways such as rmmod, modprobe, fuser, etc, but no luck.
Any idea?

**Comment by nebutech-admin** [comment]
No clue.

**Comment by spacetrain** [comment]
The problem was due to overclocking the gpus.
If I reset their clocks before killing the miner, the process finishes without any problem.
So it was a problem on my side.
Sorry for posting here.
